name: flickpicks
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/imagens/png_logo.ico"

flutter:
  uses-material-design: true
  assets:
    - assets/imagens/